# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-10-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0004_auto_20181018_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='when',
            field=models.CharField(choices=[('* * * * *', 'every minute'), ('0,5,10,15,20,25,30,35,40,45,50,55 * * * *', 'every 5 minutes'), ('0,15,30,45 * * * *', 'every 15 minutes'), ('0,30 * * * *', 'every 30 minutes'), ('0 * * * *', 'hourly'), ('0 0,6,12,18 * * *', 'every 6 hours'), ('0 0 * * *', 'daily'), ('0 0 * * 0', 'weekly'), ('0 0 1 * *', 'monthly')], max_length=255, verbose_name='When'),
        ),
    ]
