# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_letsencrypt_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhost',
            name='cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.SSLCert', verbose_name='SSL Certificate'),
        ),
    ]
