# Generated by Django 2.2.24 on 2021-09-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170116_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='access_logging',
            field=models.BooleanField(default=False, verbose_name='Enable web server access log'),
        ),
    ]
