# Generated by Django 4.1.13 on 2024-05-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_vhost_access_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable virtual host'),
        ),
    ]
