# Generated by Django 4.1.13 on 2026-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_vhost_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='php_version',
            field=models.CharField(blank=True, default='', help_text='PHP version to use for this virtual host', max_length=10, verbose_name='PHP Version'),
        ),
    ]
