# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='path',
            field=models.CharField(default='/', max_length=255),
        ),
    ]
