# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='to',
            field=models.TextField(),
        ),
    ]
